DROP DATABASE IF EXISTS shangrila CASCADE;
CREATE DATABASE IF NOT EXISTS shangrila;
SET DATABASE = shangrila;

CREATE TABLE IF NOT EXISTS users (
    id SERIAL NOT NULL PRIMARY KEY,
    email VARCHAR NOT NULL UNIQUE,
    username VARCHAR NOT NULL UNIQUE,
)
